### ISSUE TITLE
Problem to install module on Windows 7X64

### ISSUE THREAD

**Issue by wbiker** [retupmoca/P6-LibraryMake#10]
Hi!

I would like to install Inline::Perl5 on Windows, but unfortunately, installing the dependency LibraryMake failes to install:

C:\tmp>panda install Inline::Perl5
==> Inline::Perl5 depends on LibraryMake, File::Temp
==> File::Temp depends on File::Directory::Tree
==> Fetching LibraryMake
==> Building LibraryMake
Compiling lib\LibraryMake.pm6 to mbc
==> Testing LibraryMake
==> Test report submitted as: http://testers.perl6.org/reports/</html>.html
===SORRY!===
no such file or directory

Thanks

**Comment by retupmoca** [comment]
Do you have Visual Studio installed, and are you running the 'panda install' from a terminal that has 'cl.exe' in $PATH? LibraryMake will not work without a compiler available.

**Comment by wbiker** [comment]
Aaaah, facepalm. I don't have a compiler installed. That will be the problem.
