### ISSUE TITLE
README.md is UTF-16LE

### ISSUE THREAD

**Issue by zengargoyle** [retupmoca/P6-LibraryMake#13]
Seems your README.md is in UTF-16 instead of UTF-8.

**Comment by zengargoyle** [comment]
And doesn't match the POD in lib/LibraryMake.pm6 (which is what is shown by p6doc and perl6 --doc) which can make things confusing.

It would also be nice if if the ./Build.pm, ./src/Configure.pl6, and ./lib/Foo.pm6 code examples matched and used something like My::Module so that the examples pointed out that:

make("$workdir/src", "$workdir/blib/lib");
is
return Find::Bundled.find("libfoo$so", "", :throw);

and

make("$workdir/src", "$workdir/blib/lib/My/Module");
is
eturn Find::Bundled.find("libfoo$so", "My/Module", :throw);  # not My::Module

**Comment by retupmoca** [comment]
Well, it looks like I got sloppy (and also forgot that windows loves UTF-16 for some reason)! Latest commit should improve things a bit - let me know if the docs are still confusing.

**Comment by zengargoyle** [comment]
Thanks for the quick fix.
