### ISSUE TITLE
Remove Pod::Coverage dependency?

### ISSUE THREAD

**Issue by sylvarant** [retupmoca/P6-LibraryMake#16]
Hey,

This library can no longer be installed through panda due to Pod::Coverage failing.

Here's a trace from travis
```
$ panda install LibraryMake
==> LibraryMake depends on Pod::Coverage
==> Pod::Coverage depends on JSON::Tiny
==> Fetching JSON::Tiny
==> Building JSON::Tiny
==> Testing JSON::Tiny
t/01-parse.t ...... ok
t/02-structure.t .. ok
t/03-unicode.t .... ok
t/04-roundtrip.t .. ok
t/05-utf16.t ...... ok
All tests successful.
Files=5, Tests=122,  9 wallclock secs ( 0.05 usr  0.01 sys +  8.15 cusr  0.79 csys =  9.00 CPU)
Result: PASS
==> Installing JSON::Tiny
==> Successfully installed JSON::Tiny
==> Fetching Pod::Coverage
==> Building Pod::Coverage
==> Testing Pod::Coverage
Done: Job Cancelled
```
The thing is that this isn't the first time that problems with Pod::Coverage (which is still experimental) have worked their way up the chain to break this module and all of the modules that depend on it.
Could you maybe remove the dependency ?

**Comment by retupmoca** [comment]
This should already be done as of commit 050422d

You may need to do a `panda update` to get the updated dependency information. If this module is still somehow depending on Pod::Coverage, I will debug it once I get panda bootstrap working on my windows.

**Comment by sylvarant** [comment]
Thanks the module installs with no problems !
