### ISSUE TITLE
Usinf zef & panda on windows cannot install Librarymake dependency

### ISSUE THREAD

**Issue by MortalCatalyst** [retupmoca/P6-LibraryMake#18]
How do I install Librarymake on windows? 

``` powershell
C:\Users\Sayth>zef install Librarymake
===> Searching for: Librarymake
No candidates found matching: Librarymake
```

Trying to install Linenoise to get a proper repl, in both zef and panda this comes as a missing dependency.

**Comment by dwarring** [comment]
Its LibraryMake, not Librarymake

**Comment by JJ** [comment]
I guess this can be closed... Unless this is still an issue, in which case please reopen.l
