### ISSUE TITLE
Failing tests on Fedora 32

### ISSUE THREAD

**Issue by dwarring** [retupmoca/P6-LibraryMake#28]
See test failures in https://github.com/libxml-raku/LibXML-raku/issues/46

**Comment by wayland** [comment]
Hi.  I raised the original libXML issue.  

Discovery: if I run zef install LibraryMake. It turns out there were some missing prerequisite C libraries, and installing them resolved the problem:

sudo dnf install libatomic_ops-devel libuv-devel

HTH.

**Comment by wayland** [comment]
Shouldn't something be added so that these prerequisites are picked up and alerted by zef?  I wasn't clear; these prerequisite libraries were things I picked up reading the error messages, not by zef alerting me to them.  

HTH,

**Comment by dwarring** [comment]
You're right, its still an issue.

LibraryMake is testing the %LIBS setting, which LibXML isn't using anyway, so I've put in a PR to just not test it.

**Comment by wayland** [comment]
Great!  Thanks for your work on this :) .
