### ISSUE TITLE
Moving this dist to fez

### ISSUE THREAD

**Issue by 2colours** [retupmoca/P6-LibraryMake#43]
Hello,

at the moment, there is some confusion about this distribution as it still lives in p6c:
- the mentioned author is Andrew Egeler
- the repository is his (as far as I understand)
- the META6 author (and apparent maintainer), though, is JJ Merelo

The p6c ecosystem also doesn't keep different versions of the same distribution. Maybe the git tags help someone who wants to install a certain state by hand but the situation is far from ideal.

Please think about uploading this distribution to fez, and what metadata should be used for it.

**Comment by 2colours** [comment]
I don't know... ping maybe @JJ ?

**Comment by JJ** [comment]
Maybe @retupmoca could give me owner privileges? I can't, for instance, add topics to the repo (I'd like to put it up for Hacktoberfest, for instance)
