### ISSUE TITLE
Convert to three separate os test workflows

### ISSUE THREAD

**Issue by tbrowder** [retupmoca/P6-LibraryMake#44]
It would clarify needed changes if three separate .yml files were used. Use, say, linux.yml, macos.yml, and windows.yml.

For MacOS, use 'brew install' for installing OS packages (see available packages at 'https://brew.sh').

For Windows, use 'choco install' for installing OS packages (see available packages at 'https://chocolatey.org').

**Comment by JJ** [comment]
Sorry, you mean using them here or as an example?
