### ISSUE TITLE
Install failing for 1.03 on rakudo v2023.09.

### ISSUE THREAD

**Issue by coke** [retupmoca/P6-LibraryMake#48]
```
===> Testing: LibraryMake:ver<1.0.3>:auth<zef:jjmerelo>
[LibraryMake]         # Failed test 'code dies'
[LibraryMake]         # at t/01-basic.t line 35
[LibraryMake]         # You failed 1 test of 2
[LibraryMake]     # Failed test 'did we throws-like X::AdHoc?'
[LibraryMake]     # at t/01-basic.t line 35
[LibraryMake]     # You failed 1 test of 1
[LibraryMake] # Failed test 'Errors correctly if it can't'
[LibraryMake] # at t/01-basic.t line 33
[LibraryMake] # You failed 1 test of 3
===> Testing [FAIL]: LibraryMake:ver<1.0.3>:auth<zef:jjmerelo>
Aborting due to test failure: LibraryMake:ver<1.0.3>:auth<zef:jjmerelo> (use --force-test to override)
```

Found while trying to install `Terminal::LineEditor`

```
$ sw_vers
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66
```

**Comment by coke** [comment]
Note: 2 of the 3 REPL modules suggested for getting history depend on this module.

**Comment by 2colours** [comment]
I also noticed this while setting up Github Actions for Shell::DSL https://github.com/kjkuan/Shell-DSL/pull/2

**Comment by coke** [comment]
Bisecting the repo, the test starts failing with 0420c928bc1019e0788f90322ba743f7621ced72

**Comment by coke** [comment]
Some notes from reviewing the test: we try to run the failure mode test whether or not the build tools are installed, but we are expecting the chmod to control the failure mode: I would suggest we skip this as well if the tools are not installed (or make the two tests consistent).

Also, the test for whether they are installed seems broken on my mac install of rakudo. CC and LD are both `clang` which are found by `which()`, but MAKE is `/usr/bin/make` which is an executable but fails the which() call.

**Comment by coke** [comment]
> MAKE is `/usr/bin/make`

Opened linked ticket in File::Which

**Comment by JJ** [comment]
> Bisecting the repo, the test starts failing with [0420c92](https://github.com/retupmoca/P6-LibraryMake/commit/0420c928bc1019e0788f90322ba743f7621ced72)

There's no real functional change in those lines, it's just a refactoring.

**Comment by JJ** [comment]
I'll have a look anyway. But what I'm understanding here is that it's due to a downstream error?

**Comment by JJ** [comment]
> Some notes from reviewing the test: we try to run the failure mode test whether or not the build tools are installed, but we are expecting the chmod to control the failure mode: I would suggest we skip this as well if the tools are not installed (or make the two tests consistent).

OK, I can see that. Can do.

**Comment by JJ** [comment]
> > MAKE is `/usr/bin/make`
> 
> Opened linked ticket in File::Which

Thanks.
