### ISSUE TITLE
Install fails for 1.03 on rakudo v2023.10

### ISSUE THREAD

**Issue by antononcube** [retupmoca/P6-LibraryMake#50]
```
===> Testing: LibraryMake:ver<1.0.3>:auth<zef:jjmerelo>
[LibraryMake]         # Failed test 'code dies'
[LibraryMake]         # at t/01-basic.t line 35
[LibraryMake]         # You failed 1 test of 2
[LibraryMake]     # Failed test 'did we throws-like X::AdHoc?'
[LibraryMake]     # at t/01-basic.t line 35
[LibraryMake]     # You failed 1 test of 1
[LibraryMake] # Failed test 'Errors correctly if it can't'
[LibraryMake] # at t/01-basic.t line 33
[LibraryMake] # You failed 1 test of 3
===> Testing [FAIL]: LibraryMake:ver<1.0.3>:auth<zef:jjmerelo>
Aborting due to test failure: LibraryMake:ver<1.0.3>:auth<zef:jjmerelo> (use --force-test to override)
```

**Comment by JJ** [comment]
What version of Rakudo would that be?

**Comment by antononcube** [comment]
> What version of Rakudo would that be?

moar-2023.10 on macOS. But looking at some GitHub actions logs, it seems Linux too.

**Comment by JJ** [comment]
I think this might be the same issue as #48. I'll see what I can do. Thanks for the report!

**Comment by JJ** [comment]
I think the problem is that MacOS is not respecting those privs. I'll see what I can do about that.

**Comment by JJ** [comment]
[This is probably the issue here](https://stackoverflow.com/questions/17255340/chmod-unable-to-change-permissions) (and in #48)
I am not sure fixing the test is the best option here. I'll probably just disable it with Mac.
